# Generated by Django 2.1.5 on 2019-02-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_auto_20190203_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.CharField(max_length=20),
        ),
    ]
